Update MKSU_OPAce2.yml

diff --git a/.github/workflows/MKSU_OPAce2.yml b/.github/workflows/MKSU_OPAce2.yml
--- a/.github/workflows/MKSU_OPAce2.yml
+++ b/.github/workflows/MKSU_OPAce2.yml
@@ -1,10 +1,11 @@
 name: Build MKSU SUSFS For OPAce2
 on:
-  workflow_dispatch: 
+  workflow_dispatch:
+
 jobs:
   build:
     runs-on: ubuntu-latest
-    
+
     steps:
       - name: Maximize build space
         uses: easimon/maximize-build-space@master
@@ -15,11 +16,6 @@ jobs:
           remove-android: 'true'
           remove-haskell: 'true'
           remove-codeql: 'true'
-          
-      - name: Configure Git
-        run: |
-         git config --global user.name "build"
-         git config --global user.email "3436378798@qq.com"
 
       - name: Install dependencies
         run: |
@@ -41,8 +37,15 @@ jobs:
          find kernel_platform/msm-kernel/android/ -name "abi_gki_protected_exports_*" -delete
          sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion
-         sed -i '$s|echo "\$res"|echo "$res-Mortis"|' kernel_platform/common/scripts/setlocalversion            
-         sed -i '$s|echo "\$res"|echo "$res-Mortis"|' kernel_platform/msm-kernel/scripts/setlocalversion            
+         sed -i '$s|echo "\$res"|echo "$res-android12-Mortis"|' kernel_platform/common/scripts/setlocalversion            
+         sed -i '$s|echo "\$res"|echo "$res-android12-Mortis"|' kernel_platform/msm-kernel/scripts/setlocalversion            
+
+      - name: Modify kernel version in Makefile
+        run: |
+         sed -i 's/^VERSION = .*/VERSION = 5/' kernel_workspace/kernel_platform/Makefile
+         sed -i 's/^PATCHLEVEL = .*/PATCHLEVEL = 10/' kernel_workspace/kernel_platform/Makefile
+         sed -i 's/^SUBLEVEL = .*/SUBLEVEL = 209/' kernel_workspace/kernel_platform/Makefile
+         sed -i 's/^EXTRAVERSION = .*/EXTRAVERSION = -android12-Mortis/' kernel_workspace/kernel_platform/Makefile
 
       - name: Set up MKSU
         run: |
@@ -84,12 +87,22 @@ jobs:
          cd kernel_workspace
          export LTO=thin
          ./kernel_platform/oplus/build/oplus_build_kernel.sh waipio gki
-         
+
+      - name: Debug Kernel Output
+        run: |
+         ls -lR kernel_workspace/kernel_platform/out/
+
       - name: Make AnyKernel3
         run: |
          git clone https://github.com/TanakaLun/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
-         cp kernel_workspace/kernel_platform/out/msm-waipio-waipio-gki/dist/Image ./AnyKernel3/
+         IMAGE_PATH=$(find kernel_workspace/kernel_platform/out/ -name "Image" | head -n 1)
+         if [ -z "$IMAGE_PATH" ]; then
+           echo "Error: Image not found!"
+           exit 1
+         fi
+         echo "Found Image at: $IMAGE_PATH"
+         cp "$IMAGE_PATH" ./AnyKernel3/
 
       - name: Download Latest SUSFS Module
         run: |
